%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 158.40270533561804
Camera.fy: 161.01420645275138
Camera.cx: 158.8445909784188
Camera.cy: 118.05793311077254

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.bFishEye: 0

Camera.width: 320
Camera.height: 240

# Camera frames per second 
Camera.fps: 15.0

# stereo baseline times fx
Camera.bf: 10.296175847

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 35.0

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 480
LEFT.width: 752
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data:[-0.3113776747129461, 0.07787892254622376, 0.0012237754654476013, -0.001535903098170003, 0.0]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [158.40270533561804, 0.0, 161.01420645275138, 0.0, 158.8445909784188, 118.05793311077254, 0.0, 0.0, 1.0]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.9998381101157864, 0.006338420537306309, -0.016839773905392694, -0.006489211438635602, 0.9999392050711715, -0.008914947926839036, 0.01678224344350814, 0.009022781540402319, 0.9998184563800955]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [132.31197911512822, 0.0, 169.0572681427002, 8.375775999047677, 0.0, 132.31197911512822, 117.6994743347168, 0.0, 0.0, 0.0, 1.0, 0.0]

RIGHT.height: 480
RIGHT.width: 752
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data:[-0.2826663023939263, 0.05691763753929173, -0.0009349791324433419, -9.968995511958585e-05, 0.0]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [157.71678576687032, 0.0, 157.05003414095566, 0.0, 159.14408875757238, 116.65021302294838, 0.0, 0.0, 1.0]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.9969929936522403, 0.04216512132797727, -0.06501594536527881, -0.04157984102390451, 0.9990817856087032, 0.010329689508983296, 0.06539179940000726, -0.007595275394752222, 0.9978307593790177]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [132.31197911512822, 0.0, 169.0572681427002, 0.0, 0.0, 132.31197911512822, 117.6994743347168, 0.0, 0.0, 0.0, 1.0, 0.0]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

